import { Router } from 'express'
import { requireAuth } from '../middleware/auth.js'
import { supabase } from '../lib/supabase.js'

const router = Router()

// Verify the caller owns the subject (assigned_teacher_email = their email).
// Returns the subject row or throws.
async function assertSubjectOwner(subjectId, email) {
  const { data, error } = await supabase
    .from('exam_subjects')
    .select('id, class_name, subject_name, kind, branches(id, code)')
    .eq('id', subjectId)
    .eq('assigned_teacher_email', email)
    .single()
  if (error || !data) throw Object.assign(new Error('Subject not assigned to you'), { status: 403 })
  return data
}

// GET /api/paper?subjectId=&termId=
// Returns all papers for the subject+term pair.
router.get('/paper', requireAuth, async (req, res) => {
  const { subjectId, termId } = req.query
  if (!subjectId || !termId) {
    return res.status(400).json({ error: 'subjectId and termId are required' })
  }

  const email = (req.user.email || '').toLowerCase()
  try {
    const subject = await assertSubjectOwner(subjectId, email)

    const { data: papers, error } = await supabase
      .from('exam_papers')
      .select('id, paper_name, component_key, card_max, max_marks, passing_marks, exam_date, term_id, has_practical, theory_max, practical_max')
      .eq('subject_id', subjectId)
      .eq('term_id', termId)
      .order('exam_date', { ascending: true, nullsFirst: false })

    if (error) return res.status(500).json({ error: error.message })

    res.json({ papers, subject })
  } catch (e) {
    res.status(e.status || 500).json({ error: e.message })
  }
})

// POST /api/paper
// Create a new paper, or update an existing one (pass paperId to update).
// Teachers may create multiple papers per subject+term; admin marks the final one.
router.post('/paper', requireAuth, async (req, res) => {
  const { subjectId, termId, paperName, maxMarks, passingMarks, examDate, paperId,
          hasPractical, theoryMax, practicalMax } = req.body

  if (!subjectId || !termId) {
    return res.status(400).json({ error: 'subjectId and termId are required' })
  }
  // Papers are generated by the office from the report-card scoring rules
  // (Tracker → Examinations → Papers). Teachers never create or rename them,
  // and the raw max is fixed by the rule; only the exam date / passing marks
  // stay teacher-editable.
  if (!paperId) {
    return res.status(403).json({ error: 'Papers are set up by the office from the report-card rules. Ask the office if a paper is missing.' })
  }
  {
    const email0 = (req.user.email || '').toLowerCase()
    try { await assertSubjectOwner(subjectId, email0) } catch (e) { return res.status(403).json({ error: e.message }) }
    const patch = {}
    if (examDate !== undefined) patch.exam_date = examDate || null
    if (passingMarks !== undefined && passingMarks !== null && passingMarks !== '') patch.passing_marks = Number(passingMarks)
    const { data, error } = await supabase.from('exam_papers').update(patch).eq('id', paperId).eq('subject_id', subjectId).select().single()
    if (error) return res.status(500).json({ error: error.message })
    return res.json({ paper: data })
  }

  // Max-marks split (migration 079). max_marks is always the TOTAL so existing
  // report-card logic keeps working: with a practical it's theory_max +
  // practical_max; without, it's the single maxMarks the teacher entered.
  const practical = Boolean(hasPractical)
  let max_marks, theory_max, practical_max
  if (practical) {
    theory_max    = Number(theoryMax)
    practical_max = Number(practicalMax)
    if (!(theory_max >= 0) || !(practical_max >= 0) || (theory_max + practical_max) <= 0) {
      return res.status(400).json({ error: 'theoryMax and practicalMax must be non-negative and sum to > 0' })
    }
    max_marks = theory_max + practical_max
  } else {
    if (maxMarks == null) return res.status(400).json({ error: 'maxMarks is required' })
    max_marks     = Number(maxMarks)
    theory_max    = null
    practical_max = 0
  }

  const email = (req.user.email || '').toLowerCase()
  try {
    await assertSubjectOwner(subjectId, email)
  } catch (e) {
    return res.status(403).json({ error: e.message })
  }

  const payload = {
    subject_id: subjectId,
    term_id: termId,
    paper_name: paperName,
    max_marks,
    // passing_marks is NOT NULL in the schema — an explicit null bypasses the
    // column default and violates the constraint. Blank → 33% of max.
    passing_marks: passingMarks != null && passingMarks !== '' ? Number(passingMarks) : Math.ceil(max_marks * 0.33),
    exam_date: examDate || null,
    has_practical: practical,
    theory_max,
    practical_max,
  }

  if (paperId) {
    // Update — must still belong to this teacher's subject
    const { data, error } = await supabase
      .from('exam_papers')
      .update(payload)
      .eq('id', paperId)
      .eq('subject_id', subjectId)
      .select()
      .single()
    if (error) return res.status(500).json({ error: error.message })
    return res.json({ paper: data })
  }

  const { data, error } = await supabase
    .from('exam_papers')
    .insert(payload)
    .select()
    .single()
  if (error) return res.status(500).json({ error: error.message })
  res.json({ paper: data })
})

export default router
